api-version: 1.20.6
name: Typewriter
version: 0.6.0
main: com.typewritermc.engine.paper.TypewriterPaperPlugin
description: Next Generation Story Telling Plugin
authors:
- gabber235
website: https://docs.typewritermc.com
depend:
- packetevents
soft-depend:
- PlaceholderAPI
- floodgate
libraries:
- org.jetbrains.kotlin:kotlin-stdlib:2.0.21
- org.jetbrains.kotlin:kotlin-reflect:2.0.21
- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0
- com.corundumstudio.socketio:netty-socketio:1.7.19
